# Generated by Django 4.2.30 on 2026-05-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrologers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('chat', 'Chat'), ('call', 'Call'), ('video', 'Video')], default='chat', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rate_per_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('astrologer_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free_session', models.BooleanField(default=False)),
                ('agora_channel', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('astrologer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrologer_sessions', to='astrologers.astrologerprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free_tick', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_ticks', to='consultation_sessions.session')),
            ],
            options={
                'db_table': 'billing_ticks',
            },
        ),
    ]
