# Generated by Django 4.2.30 on 2026-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtick',
            name='minute_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('client_ended', 'Client Ended'), ('astrologer_ended', 'Astrologer Ended'), ('low_balance', 'Low Balance'), ('free_time_over', 'Free Time Over'), ('auto_terminated', 'Auto Terminated')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='billingtick',
            unique_together={('session', 'minute_number')},
        ),
    ]
