# Generated by Django 4.2.30 on 2026-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astrologerprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='astrologerprofile',
            name='specialties',
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Comma-separated list of languages'),
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='specialties',
            field=models.TextField(blank=True, help_text='Comma-separated list of specialties'),
        ),
    ]
