# Generated by Django 4.2.30 on 2026-05-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0002_remove_astrologerprofile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
