# Generated by Django 4.2.30 on 2026-05-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='astrologer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='session_type',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('call', 'Call'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
